/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    id("com.google.cloud.tools.jib") version("3.0.0")
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://jcenter.bintray.com")
    }
    maven {
        url = uri("https://jitpack.io")
    }
    maven {
        url = uri("https://repo.spring.io/libs-release")
    }
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.sparkjava:spark-core:2.7.1")
    implementation("org.slf4j:slf4j-simple:1.7.21")
    implementation("org.thymeleaf:thymeleaf:3.0.9.RELEASE")
    implementation("org.thymeleaf.extras:thymeleaf-extras-java8time:3.0.1.RELEASE")
    implementation("org.springframework.security:spring-security-core:4.2.3.RELEASE")
    implementation("commons-logging:commons-logging:1.2")
}

group = "com.novamaday"
version = "1.0.1"
description = "Website"
java.sourceCompatibility = JavaVersion.VERSION_1_8

jib {
    to.image = "rg.nl-ams.scw.cloud/dreamexposure/personal-site:$version"
    container {
        creationTime = "USE_CURRENT_TIMESTAMP"
    }
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
